
CREATE USER 'juanpe1' IDENTIFIED BY 'juanpe1';
#REVOKE ALL PRIVILEGES ON bd.* FROM 'juanpe1'; #TIRA ERROR PERO ANDA IGUAL, NO SE POR QUE REVOKE FROM ES ASÍ
GRANT SELECT ON bd.* TO 'juanpe1';

CREATE USER 'anagom12' IDENTIFIED BY 'anagomez';
#REVOKE ALL PRIVILEGES ON bd.* FROM 'anagom12'; #TIRA ERROR PERO ANDA IGUAL, NO SE POR QUE REVOKE FROM ES ASÍ
GRANT SELECT ON bd.* TO 'anagom12';

CREATE USER 'carli5' IDENTIFIED BY 'carlo123';
#REVOKE ALL PRIVILEGES ON bd.* FROM 'carli5'; #TIRA ERROR PERO ANDA IGUAL, NO SE POR QUE REVOKE FROM ES ASÍ
GRANT SELECT ON bd.* TO 'carli5';

CREATE USER 'marialopez123' IDENTIFIED BY 'marilo99';
#REVOKE ALL PRIVILEGES ON bd.* FROM 'marialopez123'; #TIRA ERROR PERO ANDA IGUAL, NO SE POR QUE REVOKE FROM ES ASÍ
GRANT SELECT ON bd.* TO 'marialopez123';

CREATE USER 'UserCheck'@localhost IDENTIFIED BY 'Xk9rr!23=!0A';
#REVOKE ALL PRIVILEGES ON bd.* FROM 'UserCheck';
GRANT SELECT ON bd.Usuario TO 'UserCheck';

CREATE USER 'PostLoader'@localhost IDENTIFIED BY 'Xkjjk)923=!1f';
REVOKE ALL PRIVILEGES ON bd.* FROM 'PostLoader';
GRANT SELECT ON bd.verposts TO 'PostLoader';

CREATE USER 'PostLoader'@localhost IDENTIFIED BY 'Xkjjk)923=!1f';
REVOKE ALL PRIVILEGES ON bd.* FROM 'PostLoader';
GRANT SELECT ON bd.verposts TO 'PostLoader';
